**4.1 Exercise on Functions:**

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
def convert_units(category, option, value):
    """
    Convert units based on category and option selected.

    Parameters:
    category (int): Type of conversion (1=Length, 2=Weight, 3=Volume)
    option (int): Specific conversion option
    value (float): Value to convert

    Returns:
    float: Converted result
    """

    if category == 1:  # Length
        if option == 1:
            return value * 3.28084   # meters to feet
        elif option == 2:
            return value / 3.28084   # feet to meters

    elif category == 2:  # Weight
        if option == 1:
            return value * 2.20462   # kg to lbs
        elif option == 2:
            return value / 2.20462   # lbs to kg

    elif category == 3:  # Volume
        if option == 1:
            return value * 0.264172  # liters to gallons
        elif option == 2:
            return value / 0.264172  # gallons to liters

    return None


try:
    print("Select Conversion Type")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    category = int(input("Enter your choice (1-3): "))

    if category == 1:
        print("\nLength Conversion")
        print("1. Meters (m) to Feet (ft)")
        print("2. Feet (ft) to Meters (m)")
        option = int(input("Choose option: "))
        value = float(input("Enter value: "))

        result = convert_units(category, option, value)

        if option == 1:
            print(value, "m =", result, "ft")
        elif option == 2:
            print(value, "ft =", result, "m")

    elif category == 2:
        print("\nWeight Conversion")
        print("1. Kilograms (kg) to Pounds (lbs)")
        print("2. Pounds (lbs) to Kilograms (kg)")
        option = int(input("Choose option: "))
        value = float(input("Enter value: "))

        result = convert_units(category, option, value)

        if option == 1:
            print(value, "kg =", result, "lbs")
        elif option == 2:
            print(value, "lbs =", result, "kg")

    elif category == 3:
        print("\nVolume Conversion")
        print("1. Liters (L) to Gallons (gal)")
        print("2. Gallons (gal) to Liters (L)")
        option = int(input("Choose option: "))
        value = float(input("Enter value: "))

        result = convert_units(category, option, value)

        if option == 1:
            print(value, "L =", result, "gal")
        elif option == 2:
            print(value, "gal =", result, "L")

    else:
        print("Invalid category selected.")

except ValueError:
    print("Invalid input! Please enter numeric values only.")

Select Conversion Type
1. Length
2. Weight
3. Volume
Enter your choice (1-3): 2

Weight Conversion
1. Kilograms (kg) to Pounds (lbs)
2. Pounds (lbs) to Kilograms (kg)
Choose option: 1
Enter value: 4
4.0 kg = 8.81848 lbs


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists

In [ ]:
def find_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Average value.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Find the maximum number in a list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Maximum value.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Find the minimum number in a list.

    Parameters:
    numbers (list): List of numeric values.

    Returns:
    float: Minimum value.
    """
    return min(numbers)


try:
    print("Choose the operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = int(input("Enter your choice (1-4): "))

    numbers_input = input("Enter numbers separated by spaces: ")

    numbers = [float(num) for num in numbers_input.split()]

    if len(numbers) == 0:
        print("Error: The list is empty.")
    else:
        if choice == 1:
            print("Sum =", find_sum(numbers))
        elif choice == 2:
            print("Average =", find_average(numbers))
        elif choice == 3:
            print("Maximum =", find_maximum(numbers))
        elif choice == 4:
            print("Minimum =", find_minimum(numbers))
        else:
            print("Invalid choice.")

except ValueError:
    print("Error: Please enter valid numbers only.")

Choose the operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 2
Enter numbers separated by spaces: 3 4 5 6 7
Average = 5.0


**4.2 Exercise on List Manipulation:**

1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

In [ ]:
def extract_every_other(lst):
    """
    Extract every other element from a list starting from the first element.

    Parameters:
    lst (list): The original list of elements.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.


In [ ]:
def get_sublist(lst, start, end):
    """
    Return a sublist from a list starting from index 'start' to index 'end' (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index.
    end (int): Ending index.

    Returns:
    list: Sublist from start to end.
    """
    return lst[start:end+1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print("Original list:", numbers)
print("Sublist:", result)

Original list: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.


In [ ]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print("Original list:", numbers)
print("Reversed list:", result)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.


In [ ]:
def remove_first_last(lst):
    """
    Remove the first and last elements of a list.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]


# Example
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print("Original list:", numbers)
print("After removing first and last elements:", result)

Original list: [1, 2, 3, 4, 5]
After removing first and last elements: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.


In [ ]:
def get_first_n(lst, n):
    """
    Return the first n elements from a list.

    Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract from the beginning.

    Returns:
    list: A new list containing the first n elements.
    """
    return lst[:n]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print("Original list:", numbers)
print("First n elements:", result)

Original list: [1, 2, 3, 4, 5]
First n elements: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(lst, n):
    """
    Return the last n elements from a list.

    Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.
    """
    return lst[-n:]


# Example
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print("Original list:", numbers)
print("Last n elements:", result)

Original list: [1, 2, 3, 4, 5]
Last n elements: [4, 5]


7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.


In [ ]:
def reverse_skip(lst):
    """
    Extract every second element from a list in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list containing elements in reverse order, skipping one element each time.
    """
    return lst[-2::-2]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print("Original list:", numbers)
print("Reversed and skipped elements:", result)

Original list: [1, 2, 3, 4, 5, 6]
Reversed and skipped elements: [5, 3, 1]


**4.3 Exercise on Nested List:**

**1. Flatten a Nested List:**
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [ ]:
def flatten(lst):
    """
    Flatten a nested list into a single list.

    Parameters:
    lst (list): A nested list containing sublists.

    Returns:
    list: A flattened list containing all elements.
    """
    flat_list = []

    for sublist in lst:
        for item in sublist:
            flat_list.append(item)

    return flat_list


# Example
numbers = [[1, 2], [3, 4], [5]]
result = flatten(numbers)

print("Original nested list:", numbers)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**
Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_element(lst, indices):
    """
    Access a specific element from a nested list using given indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices showing the position of the element.

    Returns:
    element: The element at the specified position.
    """
    element = lst

    for index in indices:
        element = element[index]

    return element


# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)

print("Nested List:", lst)
print("Indices to access:", indices)
print("Element at position", indices, "is:", result)

Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices to access: [1, 2]
Element at position [1, 2] is: 6


**3. Sum of All Elements in a Nested List:**
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [ ]:
def sum_nested(lst):
    """
    Calculate the sum of all numbers in a nested list.

    Parameters:
    lst (list): A nested list that may contain numbers or other lists.

    Returns:
    int/float: Sum of all numbers in the nested list.
    """
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)   # recursive call for sublist
        else:
            total += item

    return total


# Example
numbers = [[1, 2], [3, [4, 5]], 6]

result = sum_nested(numbers)

print("Nested List:", numbers)
print("Sum of all elements:", result)

Nested List: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


**4. Remove Specific Element from a Nested List:**
Write a Python function that removes all occurrences of a specific element from a nested list.

In [ ]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): A nested list that may contain other lists.
    elem: The element to remove.

    Returns:
    list: Modified list with the element removed.
    """
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))  # process sublist
        elif item != elem:
            result.append(item)

    return result


# Example
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

result = remove_element(lst, elem)

print("Original Nested List:", lst)
print("Element to remove:", elem)
print("Modified List:", result)

Original Nested List: [[1, 2], [3, 2], [4, 5]]
Element to remove: 2
Modified List: [[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**
Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [ ]:
def find_max(lst):
    """
    Find the maximum element in a nested list.

    Parameters:
    lst (list): A nested list that may contain numbers or other lists.

    Returns:
    int/float: The maximum element in the nested list.
    """
    maximum = None

    for item in lst:
        if isinstance(item, list):
            value = find_max(item)  # recursive call
        else:
            value = item

        if maximum is None or value > maximum:
            maximum = value

    return maximum


# Example
numbers = [[1, 2], [3, [4, 5]], 6]

result = find_max(numbers)

print("Nested List:", numbers)
print("Maximum element in the nested list:", result)

Nested List: [[1, 2], [3, [4, 5]], 6]
Maximum element in the nested list: 6


**6. Count Occurrences of an Element in a Nested List:**
Write a Python function that counts how many times a specific element appears in a nested list.

In [ ]:
def count_occurrences(lst, elem):
    """
    Count how many times a specific element appears in a nested list.

    Parameters:
    lst (list): A nested list that may contain numbers or other lists.
    elem: The element to count.

    Returns:
    int: Number of times the element appears.
    """
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # recursive call
        elif item == elem:
            count += 1

    return count


# Example
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

result = count_occurrences(lst, elem)

print("Nested List:", lst)
print("Element to count:", elem)
print("Number of occurrences:", result)

Nested List: [[1, 2], [2, 3], [2, 4]]
Element to count: 2
Number of occurrences: 3


**7. Flatten a List of Lists of Lists:**
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [ ]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list.

    Parameters:
    lst (list): A list that may contain other nested lists.

    Returns:
    list: A single flattened list containing all elements.
    """
    flat_list = []

    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # recursive call
        else:
            flat_list.append(item)

    return flat_list


# Example
lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

result = deep_flatten(lst)

print("Original Nested List:", lst)
print("Flattened List:", result)

Original Nested List: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**
Write a Python function that calculates the average of all elements in a nested list.

In [ ]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.

    Parameters:
    lst (list): A nested list containing numbers or other lists.

    Returns:
    float: The average of all elements.
    """
    total = 0
    count = 0

    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1

    return total, count


# Example
lst = [[1, 2], [3, 4], [5, 6]]

total, count = average_nested(lst)
average = total / count

print("Nested List:", lst)
print("Average of all elements:", average)

Nested List: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


**To- Do- NumPy**

**10.1 Basic Vector and Matrix Operation with Numpy.**

**Problem- 1: Array Creation:**

1. Initialize an empty array with size 2X2.

In [4]:
import numpy as np

zeros_array = np.zeros((2, 2))
print(zeros_array)


[[0. 0.]
 [0. 0.]]


2. Initialize an all one array with size 4X2.

In [6]:
# Create ones array 4x2
ones_array = np.ones((4, 2))
print("Ones array (4x2):\n", ones_array)

Ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [7]:
# Array of shape 3x3, filled with 7
filled_array = np.full((3, 3), 7)
print("Array filled with 7 (3x3):\n", filled_array)

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}


In [9]:
# Zeros array like ones_array
zeros_like_array = np.zeros_like(ones_array)
print("Zeros array like ones_array:\n", zeros_like_array)

Zeros array like ones_array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}


In [11]:
# Ones array like ones_array
ones_like_array = np.ones_like(ones_array)
print("Ones array like ones_array:\n", ones_like_array)

Ones array like ones_array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [12]:
# Convert list to numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("List converted to NumPy array:\n", array_from_list)

List converted to NumPy array:
 [1 2 3 4]


**Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:**

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [13]:
import numpy as np

# Array from 10 to 49 (inclusive start, exclusive end)
array1 = np.arange(10, 50)
print("Array from 10 to 49:\n", array1)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.


In [14]:
# 1D array from 0 to 8
array2_1d = np.arange(9)

# Reshape to 3x3 matrix
matrix_3x3 = array2_1d.reshape((3, 3))
print("3x3 Matrix:\n", matrix_3x3)

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}


In [15]:
# Identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.


In [16]:
# Random array of size 30
random_array = np.random.random(30)

# Mean of the array
mean_value = random_array.mean()
print("Random Array (size 30):\n", random_array)
print("Mean of the array:", mean_value)

Random Array (size 30):
 [0.80767603 0.67813064 0.35763091 0.48509025 0.61256352 0.4485061
 0.88855365 0.06445302 0.27290515 0.22134281 0.30301819 0.35790902
 0.60179491 0.38543898 0.10627411 0.90245248 0.43676379 0.65119165
 0.84061477 0.6475095  0.53290323 0.49695444 0.10029167 0.70030204
 0.34534894 0.20479635 0.53059748 0.39758031 0.6379717  0.75498775]
Mean of the array: 0.4923851122994799


5. Create a 10X10 array with random values and find the minimum and maximum values.


In [17]:
# 10x10 random array
array_10x10 = np.random.random((10, 10))

# Minimum and maximum
min_value = array_10x10.min()
max_value = array_10x10.max()
print("10x10 Random Array:\n", array_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

10x10 Random Array:
 [[0.89404903 0.88888255 0.3321433  0.98082708 0.16557281 0.09714516
  0.01373014 0.82782154 0.22208728 0.71299356]
 [0.91459447 0.966576   0.1515224  0.13394108 0.43259834 0.82109955
  0.42353873 0.52467282 0.19993471 0.64941905]
 [0.04802686 0.80930951 0.32396591 0.66539735 0.21410454 0.82417977
  0.04126346 0.33202498 0.79959137 0.30272175]
 [0.09235131 0.17994271 0.33581296 0.81965876 0.50103858 0.40379777
  0.14714461 0.48317523 0.40509603 0.30934415]
 [0.58816314 0.97267837 0.19524126 0.40908483 0.87708628 0.929417
  0.75247904 0.1853156  0.01634827 0.14117435]
 [0.47977276 0.90371719 0.30439668 0.81963271 0.27851887 0.96013274
  0.1612464  0.8392508  0.4985425  0.8048652 ]
 [0.57679286 0.97904117 0.62231625 0.91545909 0.43693214 0.45980695
  0.00293052 0.4205778  0.75954583 0.04722723]
 [0.41665239 0.92318008 0.29990607 0.69526495 0.58352948 0.94079921
  0.70787759 0.93136786 0.21366245 0.32999398]
 [0.50812399 0.41192434 0.00448202 0.14863629 0.53422737 0.80

6. Create a zero array of size 10 and replace 5th element with 1.


In [18]:
# Zero array
zero_array = np.zeros(10)

# Replace 5th element (index 4)
zero_array[4] = 1
print("Zero array with 5th element replaced by 1:\n", zero_array)

Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].


In [19]:
arr = np.array([1, 2, 0, 0, 4, 0])

# Reverse using slicing
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.


In [20]:
# Create a 5x5 array of ones
border_array = np.ones((5, 5))

# Set inner elements to zero
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on border and 0 inside:\n", border_array)

2D Array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.


In [21]:
# Create 8x8 zeros array
checkerboard = np.zeros((8, 8))

# Fill checkerboard pattern
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem- 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

In [51]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x:\n", x)
print("\n y:\n", y)
print("\n v:", v)
print("\n w:", w)

x:
 [[1 2]
 [3 5]]

 y:
 [[5 6]
 [7 8]]

 v: [ 9 10]

 w: [11 12]


1. Add the two array.

In [23]:
add_xy = x + y
print("x + y:\n", add_xy)

x + y:
 [[ 6  8]
 [10 13]]


2. Subtract the two array.

In [24]:
sub_xy = x - y
print("x - y:\n", sub_xy)

x - y:
 [[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.


In [25]:
mult_x = x * 3
print("x * 3:\n", mult_x)

x * 3:
 [[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.


In [26]:
square_x = x ** 2
print("Square of x:\n", square_x)

Square of x:
 [[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [34]:
#Dot product of v and w
dot_vw = np.dot(v, w)
print("Dot product v . w:", dot_vw)

Dot product v . w: 219


In [36]:
#Dot product of x and v
dot_xv = np.dot(x, v)
print("Dot product x . v:\n", dot_xv)

Dot product x . v:
 [29 77]


In [38]:
#Dot product of x and y
dot_xy = np.dot(x, y)
print("Dot product x . y:\n", dot_xy)

Dot product x . y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.


In [28]:
#Concatenate x and y along rows (vertically)
concat_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_row)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [30]:
#Concatenate v and w along column (as 2D arrays)
# First convert 1D arrays to 2D column vectors
v_col = v.reshape(2, 1)
w_col = w.reshape(2, 1)

concat_col = np.concatenate((v_col, w_col), axis=1)
print("Concatenate v and w along column:\n", concat_col)

Concatenate v and w along column:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [31]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Task 7 - Concatenate x and v:\n", concat_xv)
except ValueError as e:
    print("Task 7 - Error:", e)

Task 7 - Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [33]:
#Fixed concatenation
v_row = v.reshape(1, 2)
concat_fixed = np.concatenate((x, v_row), axis=0)
print("Fixed concatenation (x and v_row):\n", concat_fixed)

Fixed concatenation (x and v_row):
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


**Problem- 4: Matrix Operations:**

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

In [50]:
import numpy as np

A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

print("Matrix A:\n", A)
print("\n Matrix B:\n", B)

Matrix A:
 [[3 4]
 [7 8]]

 Matrix B:
 [[5 3]
 [2 1]]


1. Prove A.A−1 = I.

In [49]:
# Inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
result1 = np.dot(A, A_inv)

# Identity matrix for comparison
I = np.eye(2)

print("A * A_inv:\n", result1)
print("\n Identity Matrix I:\n", I)

# Check if result is close to identity
print("\n Is A * A_inv approximately equal to I?", np.allclose(result1, I))

A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 Identity Matrix I:
 [[1. 0.]
 [0. 1.]]

 Is A * A_inv approximately equal to I? True


2. Prove AB̸ = BA.


In [47]:
# Multiply AB
AB = np.dot(A, B)

# Multiply BA
BA = np.dot(B, A)

print("AB:\n", AB)
print("\n BA:\n", BA)

# Check equality
print("\n Is AB equal to BA?", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]

 BA:
 [[36 44]
 [13 16]]

 Is AB equal to BA? False


3. Prove (AB)T = BTAT.


In [45]:
# Transpose of AB
AB_T = np.dot(A, B).T

# Product of transposes in reverse order
BT_AT = np.dot(B.T, A.T)

print("(AB)^T:\n", AB_T)
print("\n B^T * A^T:\n", BT_AT)

# Check equality
print("\n Is (AB)^T equal to B^T * A^T?", np.array_equal(AB_T, BT_AT))

(AB)^T:
 [[23 51]
 [13 29]]

 B^T * A^T:
 [[23 51]
 [13 29]]

 Is (AB)^T equal to B^T * A^T? True


• Solve the following system of Linear equation using Inverse Methods.
2x −3y+z =−1
x −y+2z =−3
3x +y−z =9

In [52]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constants matrix B
B = np.array([-1, -3, 9])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

print("Solution of the system [x, y, z]:\n", X)

Solution of the system [x, y, z]:
 [ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function.

In [53]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constants vector B
B = np.array([-1, -3, 9])

In [54]:
# Compute inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse
X = np.dot(A_inv, B)

print("Solution of the system [x, y, z]:\n", X)

Solution of the system [x, y, z]:
 [ 2.  1. -2.]


In [56]:
#Verification
# Verify A * X ≈ B
B_check = np.dot(A, X)
print("Check A * X:\n", B_check)
print("\n Original B:\n", B)
print("\n Is solution correct?", np.allclose(B_check, B))

Check A * X:
 [-1. -3.  9.]

 Original B:
 [-1 -3  9]

 Is solution correct? True
